export const JWT_ACCESS_TOKEN_EXPIRATION_MS = 'JWT_ACCESS_TOKEN_EXPIRATION_MS';
export const JWT_REFRESH_TOKEN_EXPIRATION_MS =
  'JWT_REFRESH_TOKEN_EXPIRATION_MS';
export const JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';
export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
export const AUTH_UI_REDIRECT = 'AUTH_UI_REDIRECT';

export const GOOGLE_AUTH_CLIENT_ID = 'GOOGLE_AUTH_CLIENT_ID';
export const GOOGLE_AUTH_CLIENT_SECRET = 'GOOGLE_AUTH_CLIENT_SECRET';
export const GOOGLE_AUTH_REDIRECT_URI = 'GOOGLE_AUTH_REDIRECT_URI';
